version: '3.9'

services:
  php-env:
    build:
      context: .  
      dockerfile: Dockerfile 
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    #command: --default-authentication-plugin=mysql_native_password
    restart: no
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./db_data/:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      PMA_ARBITRARY: 1  
    depends_on:
      - mysql_db
