version: "3.1"

services:
  mysql:
    image: mysql
    restart: no
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./db_data/:/var/lib/mysql